<?php namespace App\TTC\Models\Survey\Entity\Logic;

use App\TTC\Chain\ChainPayload;
use App\TTC\Chain\Payload\GetPayload;
use App\TTC\Exceptions\Chain\InvalidPayloadException;
use App\TTC\Models\Survey\Entity\BaseEntity;

/**
 * App\TTC\Models\Survey\Entity\Logic\BaseLogic
 *
 */
class BaseLogic extends BaseEntity
{
    public $canBePresented = false;

    public function handleChain(ChainPayload $payload)
    {
        if ($payload instanceof GetPayload) {
            throw new InvalidPayloadException("Logic entities cannot handle GET payloads.");
        }

        parent::handleChain($payload); // TODO: Change the autogenerated stub
    }


}
